apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/ec2-user/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops-tools
  name: jenkins-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi