---
- name: Configure Jenkins on EKS Cluster
  hosts: all
  gather_facts: no

  tasks:
    - name: apt update
      apt:
        update_cache: yes
      become: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
      become: yes
      notify: Update kubeconfig for EKS cluster
    
  handlers:
    - name: Update kubeconfig for EKS cluster
      shell: aws eks --region "us-east-1" update-kubeconfig --name Fixeds-eks
      notify: Create namespace for Jenkins and Jenkins agent

    - name: Create namespace for Jenkins and Jenkins agent
      shell: kubectl create namespace devops-tools
      notify: Adding proxy

    - name: Adding proxy
      shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      notify: install proxy 

    - name: install proxy 
      shell: helm install ingress-nginx ingress-nginx/ingress-nginx 
    - name: Apply YAML files for Jenkins
      shell: kubectl apply -f k8s/.
      args:
        chdir: ~




